INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Death Be Not Proud', '58590', 'wglqm6zj0h', 29);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Taming a Sea Horse', '18856-5634', 'm2y9v6f9af', 21);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Those Barren Leaves, Thrones, Dominations', '47402-4960', 'ka4g5gvnjj', 53);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('O Pioneers!', '19628', 'uqlj8qm45n', 43);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('A Darkling Plain', '06637', 'azfq40wqqi', 28);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Absalom, Absalom!', '03460-6209', 'wpytle24ri', 41);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('To Say Nothing of the Dog', '89094', 'evymzs7f10', 29);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('For Whom the Bell Tolls', '78549-5013', 'zvd4qsws6d', 59);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('All Passion Spent', '57343', 'cvb2zialyl', 42);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('All Passion Spent', '85318', 've28puj2u3', 42);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('In Death Ground', '15861-3584', 'k95og93jlj', 31);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('For a Breath I Tarry', '92841-3885', 't26kn3nlxk', 19);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Moon by Night', '54214', 'ip1agnhjby', 58);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Bury My Heart at Wounded Knee', '32215-1733', 'c4gmm0v5zx', 59);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Grapes of Wrath', '52331', '7fq2q18iyn', 68);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('In a Glass Darkly', '91722-5938', 'nnnlaibda8', 29);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Down to a Sunless Sea', '62723', 'szxdlcgqt7', 51);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Nine Coaches Waiting', '32294', 'fv79msrbw8', 44);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Consider the Lilies', '35644-3989', 'z8geagi3qc', 66);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('An Instant In The Wind', '14642-7085', '4eu29ovqoo', 32);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Monkey''s Raincoat', '91628-3284', 'i93sqqnv6r', 71);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Of Human Bondage', '37338-9834', 'n0kf388v58', 35);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Curious Incident of the Dog in the Night-Time', '59914', 'whm2a3j3c1', 43);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Last Temptation', '17148', '54i7xmaqds', 28);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Butter In a Lordly Dish', '10729-2169', 'm411g622s1', 54);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Jacob Have I Loved', '66972', '3jbcuc1ois', 28);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('A Confederacy of Dunces', '89816', 'vb71g2m11w', 25);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Nectar in a Sieve', '08330-6713', 'ht8yt3mk4z', 27);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Consider Phlebas', '88189', '8nvkoqlhuk', 44);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Dance Dance Dance', '13167-6814', '9q33rc3cgt', 71);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('A Time to Kill', '41611-9501', 'qa7ajbzmc9', 71);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Man Within', '82823', 'q9rvgvr96n', 42);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Lilies of the Field', '44916-4108', 'gq6jg7q1mc', 41);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Frequent Hearses', '60645', '5m1qhsvhwh', 21);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Absalom, Absalom!', '97915-5856', 'h7gh8fmzhh', 71);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Dulce et Decorum Est', '53935', '1f8tenhkww', 66);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Fear and Trembling', '03318', 'oq0zfu5lkn', 56);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Mirror Crack''d from Side to Side', '10853-6762', 'o2dmr5z3xn', 64);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Skull Beneath the Skin', '05194', 'l8b5ng7bt6', 49);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Mr Standfast', '65852', 'yt4zk7d1fw', 48);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Consider Phlebas', '18245', 'ewsuif66jq', 60);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Blood''s a Rover', '44961-3109', 'bqokxpn6tv', 61);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Oh! To be in England', '71854-8921', 'nyvtc3klje', 44);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('A Time to Kill', '64961', 'iu8e5vmkb2', 32);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Daffodil Sky', '84741-8986', 'hrypwo89lq', 55);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Consider Phlebas', '25844-8647', 'uldu7ck7zn', 47);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Wind''s Twelve Quarters', '55937-4922', '901vjh2dps', 32);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Road Less Traveled', '96462-5809', 'rx2tyir5xi', 63);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('A Confederacy of Dunces', '48745-1786', 'qmcmen7jsv', 49);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('East of Eden', '82463', 'xvpwgme1kk', 28);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Far-Distant Oxus', '99735-3457', 't8f43rpj73', 47);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Waiting for the Barbarians', '68738-9985', 'ihciymfa4r', 37);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Moving Toyshop', '63444', 'rcmt1prgad', 69);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Stranger in a Strange Land', '98060-5005', 'us210d0xts', 25);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('All the King''s Men', '31142', '43328w6f8h', 69);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Little Hands Clapping', '04146-2174', 'nv1fozamhd', 58);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Waiting for the Barbarians', '38239-7951', 'zqc70o945o', 47);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Waste Land', '48480-6477', 'm9zq85jfu1', 49);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('In Death Ground', '58343', 'rsqd17gk2m', 41);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Look Homeward, Angel', '40391', '21g6qbv5vu', 50);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('I Sing the Body Electric', '75458-0391', 'ae9jt4yagf', 20);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Man Within', '80296-4485', 'ii4a1c4iik', 53);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('To Say Nothing of the Dog', '58465-6783', '272pnp084e', 53);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Sun Also Rises', '96579-0259', 'njyd92bmzo', 41);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Fame Is the Spur', '47385', '3wp0segqkq', 65);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Many Waters', '24383-1884', 'mkwybjxhlo', 63);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Curious Incident of the Dog in the Night-Time', '05720', '9z36khdc42', 37);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('A Passage to India', '90011', 'vt87arv6yi', 23);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Specimen Days', '65724', 'xgmq2u6ogw', 27);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Green Bay Tree', '87843', 'lhhphjk89m', 40);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('After Many a Summer Dies the Swan', '59404', 'hjk7giic9h', 69);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('A Handful of Dust', '33040', 'i0qiyu3oiv', 40);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Blood''s a Rover', '82684', 'j2oar5o7ug', 44);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('A Darkling Plain', '54548-6466', '1q55dmmmz9', 27);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Lathe of Heaven', '67884', 'j7k2ezjbd0', 45);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Heart Is a Lonely Hunter', '67839-0089', 'wfxtdcsala', 28);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Moving Toyshop', '94337-0431', 'v7b9fuvvl6', 49);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Gone with the Wind', '22885-8877', 'ytknppx7at', 20);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Soldier''s Art', '18861-2186', 'nx83mm9v77', 57);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Far-Distant Oxus', '46596-4818', '3u9ns7g1rs', 29);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Look Homeward, Angel', '48364-1545', 'dgpu07aump', 28);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('To Say Nothing of the Dog', '67529-1826', 'uf2vpga397', 40);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Jacob Have I Loved', '49215-4058', 'ksqjt0qc9p', 47);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('An Evil Cradling', '36304', '8i8wuiogib', 28);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Blithe Spirit', '90743-5557', 'gz7jvkwimm', 21);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Butter In a Lordly Dish', '86660', '4fp66v0ypf', 47);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Curious Incident of the Dog in the Night-Time', '40097-1253', '5f6x9biyb1', 60);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Waiting for the Barbarians', '29497-5416', 'oh5mjt7ngi', 63);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('To Sail Beyond the Sunset', '55035', 'ufwolg52us', 72);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Wind''s Twelve Quarters', '64211', '7t7bcurhry', 27);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Blood''s a Rover', '09030-3104', 'xbbjygibza', 62);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('This Side of Paradise', '89960-3681', 'u2ukvmh911', 56);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('In a Dry Season', '69771', 'l96xm3ksvy', 72);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Dance Dance Dance', '65009-9072', 'fx08lmmz47', 61);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Blue Remembered Earth', '79911', '2p0010xozt', 53);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('East of Eden', '73372', 'qqm01zt5lh', 34);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('The Last Temptation', '78471-9420', '4uizzz8upk', 24);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('This Side of Paradise', '99463', 'bewvy6b6mf', 21);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('Time To Murder And Create', '44737', 'bafnx84e0k', 19);
INSERT INTO phantom (BOOK_TITLE, ZIP_CODE, CHARACTERS, AGE) VALUES ('All Passion Spent', '93009-2162', 'wi1vfbe4mf', 56);